### ISSUE TITLE
Add example of dates and date_format property to settings.py

### ISSUE THREAD

**Issue by ola-rende** [nicolaiarocci/eve-demo#15]
It would be very helpful to see an example of how to work with dates in general and date_format in particular in this demo, as these are very common use cases. The documentation only briefly touches the subject of date_format, and provides no examples.

**Comment by nicolaiarocci** [comment]
I agree that the eve docs need a dates example as many people have been confused in the past. Would you open a ticket in the eve repository itself?

**Comment by ola-rende** [comment]
Done: https://github.com/nicolaiarocci/eve/issues/924

**Comment by ernests** [comment]
I'm still struggling finding proper example with DATE_FORMAT. I need to post datetime with json.dumps and getting erro
